# hexo-theme-indigo
# https://github.com/SatoMasuda/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       メニューに表示されるテキスト。省略した場合、デフォルトはアイコンと同じ。最初の文字は大文字になる。
#    url: /about       絶対パスまたは相対パス、必須。
#    target: _blank    ポップアップするかどうか、省略した場合は現在のページで開く
menu:
  home:
    text: Home
    url: /
  archives:
    url: /archives
  tags:
    url: /tags
  th-list:
    text: Categories
    url: /categories
  github:
    url: https://github.com/<input-your-github-id>
    target: _blank
  link:
    text: Test
    url: /custom

# アバターのURL
avatar: /img/avatar.jpg
# avatar link
avatar_link: /
# アバターの背景
brand: /img/brand.jpg
# favicon
favicon: /favicon.ico

# email
email: <input-your-email-address>

# 色の設定 （例はAndroid L Chrome のステータスバーの色）
color: '#3F51B5'

# ページタイトル
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 記事の要約
excerpt_render: false
excerpt_length: 200
excerpt_link: 全文を読む...
mathjax: false
archive_yearly: true

# 記事の最終更新時刻を表示するかどうか
show_last_updated: true

# 共有を開くかどうか
share: true

# 報酬を開くか、報酬を閉じるか。(:false)
reward:
  title: おじいさんありがとうございます〜
  wechat: /img/wechat.jpg     #微信，关闭设为 false
  alipay: /img/alipay.jpg     #支付宝，关闭设为 false

# 検索機能を有効化するか
search: true

# メニューナビゲーションを表示するか
hideMenu: true

# 目次(toc)を表示するか
# toc: false
toc:
  list_number: true  # ナンバリングするか

# ページ末尾の内容。すべての変数およびhexoの補助関数を呼び出すことができる。hexo.ioを参照。
postMessage: ここで作成者のメッセージを記述できます。タグ内ですべての変数とhexoの補助関数を呼び出すことができます。例：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# CNZZ(中国のトラフィック統計サイト)を使用するか、使用する場合はidを入力(cnzz: 123456789)
cnzz: false

# Baidu分析。(:false|:<your-key>)
baidu_tongji: false

# Tencent分析。(:false|:<your-id>)
tajs: false

# google
google_analytics: false
google_site_verification: false

# sogou站长验证 http://zhanzhang.sogou.com/
sogou_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# use gitalk://github.com/gitalk/gitalk
gitalk: false
#  owner: 
#  repo: 
#  client_id: 
#  client_secret: 

# Valine Comment system. https://valine.js.org
valine:
  enable: false # 如果你想使用valine，请将值设置为 true
  appId:  # your leancloud appId
  appKey:  # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Just go go # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# 是否开启Hyper Comments，填写id则启用，false则禁用。http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false


# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2015

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 用户页面中作者相关的描述性文字，如不需要设为 false

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 站点总访问量：

# 动态定义title
title_change:
  normal: (つェ⊂)咦!又好了!
  leave: 死鬼去哪里了！

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: true

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: false
